import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import { Data } from "./api/tasks";

const Tasks: NextPage = () => {
  const [data, setData] = React.useState<Data[] | null>(null);
  const [isLoading, setIsLoading] = React.useState<boolean>(true);

  React.useEffect(() => {
    fetch("/api/tasks")
      .then((res) => res.json())
      .then((tasks) => {
        setData(tasks);
        setIsLoading(false);
      })
      .catch((error) =>
        console.error(`There was an error fetching the data ${error}`)
      );
  }, []);

  if (isLoading) {
    return <p>Loading data...</p>;
  }
  if (!data) return <p>No profile data</p>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {data &&
            data.map(({ name, status }, idx) => (
              <li key={idx}>
                <p>{name}</p>
                <p>
                  Status: <span style={{ color: "blue" }}>{status}...</span>{" "}
                </p>
              </li>
            ))}
        </ul>
      </main>
    </div>
  );
};

export default Tasks;
